function [varargout] = freesurfer_statsurf_plot(FSAverageV, FSAverageF, FaceVertexCData, FreesurferSeedType, ...
	ValuesMask, CMAPX, CMAPIMG, LegendXTick, LegendXTickLabels, options)

% plots the stat surfaces

%
% VariablesNeeded = {'ValuesMask', 'FSAverageVInflated', 'FSAverageF', 'FreesurferSeedType', ...
% 	'LegendLabel', 'CMAPX', 'CMAPIMG', 'LegendXTick', 'LegendXTickLabels', 'MainTitle'};
%
% for z = 1:length(VariablesNeeded)
% 	if(exist(VariablesNeeded{z}, 'var') ~= 1)
% 		error(['Variable does not exist: ' VariablesNeeded{z}]);
% 	end
% end

[APARCLabels{1:2}] = deal({'bankssts', 'caudalanteriorcingulate', 'caudalmiddlefrontal', ...
	'cuneus', 'entorhinal', 'fusiform', ...
	'inferiorparietal', 'inferiortemporal', 'isthmuscingulate', ...
    'lateraloccipital', 'lateralorbitofrontal', 'lingual', ...
	'medialorbitofrontal', 'middletemporal',  'parahippocampal', ...
    'paracentral', 'parsopercularis', 'parsorbitalis', ...
    'parstriangularis', 'pericalcarine', 'postcentral', ...
    'posteriorcingulate', 'precentral', 'precuneus', ...
    'rostralanteriorcingulate', 'rostralmiddlefrontal', 'superiorfrontal', ...
    'superiorparietal', 'superiortemporal', 'supramarginal', ...
    'frontalpole', 'temporalpole', 'transversetemporal', 'insula'});

[DKTLabels{1:2}] = deal({'caudalanteriorcingulate', 'caudalmiddlefrontal', ...
	'cuneus', 'entorhinal', 'fusiform', ...
	'inferiorparietal', 'inferiortemporal', 'isthmuscingulate', ...
    'lateraloccipital', 'lateralorbitofrontal', 'lingual', ...
	'medialorbitofrontal', 'middletemporal',  'parahippocampal', ...
    'paracentral', 'parsopercularis', 'parsorbitalis', ...
    'parstriangularis', 'pericalcarine', 'postcentral', ...
    'posteriorcingulate', 'precentral', 'precuneus', ...
    'rostralanteriorcingulate', 'rostralmiddlefrontal', 'superiorfrontal', ...
    'superiorparietal', 'superiortemporal', 'supramarginal', ...
    'transversetemporal', 'insula'});

[HCPMMP1Labels{1:2}] = deal({'Primary_Visual_Cortex',...
'Medial_Superior_Temporal_Area',...
'Sixth_Visual_Area',...
'Second_Visual_Area',...
'Third_Visual_Area',...
'Fourth_Visual_Area',...
'Eighth_Visual_Area',...
'Primary_Motor_Cortex',...
'Primary_Sensory_Cortex',...
'Frontal_Eye_Fields',...
'Premotor_Eye_Field',...
'Area_55b',...
'Area_V3A',...
'RetroSplenial_Complex',...
'Parieto-Occipital_Sulcus_Area_2',...
'Seventh_Visual_Area',...
'IntraParietal_Sulcus_Area_1',...
'Fusiform_Face_Complex',...
'Area_V3B',...
'Area_Lateral_Occipital_1',...
'Area_Lateral_Occipital_2',...
'Posterior_InferoTemporal_complex',...
'Middle_Temporal_Area',...
'Primary_Auditory_Cortex',...
'PeriSylvian_Language_Area',...
'Superior_Frontal_Language_Area',...
'PreCuneus_Visual_Area',...
'Superior_Temporal_Visual_Area',...
'Medial_Area_7P',...
'Area_7m',...
'Parieto-Occipital_Sulcus_Area_1',...
'Area_23d',...
'Area_ventral_23_a+b',...
'Area_dorsal_23_a+b',...
'Area_31p_ventral',...
'Area_5m',...
'Area_5m_ventral',...
'Area_23c',...
'Area_5L',...
'Dorsal_Area_24d',...
'Ventral_Area_24d',...
'Lateral_Area_7A',...
'Supplementary_and_Cingulate_Eye_Field',...
'Area_6m_anterior',...
'Medial_Area_7A',...
'Lateral_Area_7P',...
'Area_7PC',...
'Area_Lateral_IntraParietal_ventral',...
'Ventral_IntraParietal_Complex',...
'Medial_IntraParietal_Area',...
'Area_1',...
'Area_2',...
'Area_3a',...
'Dorsal_area_6',...
'Area_6mp',...
'Ventral_Area_6',...
'Area_Posterior_24_prime',...
'Area_33_prime',...
'Anterior_24_prime',...
'Area_p32_prime',...
'Area_a24',...
'Area_dorsal_32',...
'Area_8BM',...
'Area_p32',...
'Area_10r',...
'Area_47m',...
'Area_8Av',...
'Area_8Ad',...
'Area_9_Middle',...
'Area_8B_Lateral',...
'Area_9_Posterior',...
'Area_10d',...
'Area_8C',...
'Area_44',...
'Area_45',...
'Area_47l_(47_lateral)',...
'Area_anterior_47r',...
'Rostral_Area_6',...
'Area_IFJa',...
'Area_IFJp',...
'Area_IFSp',...
'Area_IFSa',...
'Area_posterior_9-46v',...
'Area_46',...
'Area_anterior_9-46v',...
'Area_9-46d',...
'Area_9_anterior',...
'Area_10v',...
'Area_anterior_10p',...
'Polar_10p',...
'Area_11l',...
'Area_13l',...
'Orbital_Frontal_Complex',...
'Area_47s',...
'Area_Lateral_IntraParietal_dorsal',...
'Area_6_anterior',...
'Inferior_6-8_Transitional_Area',...
'Superior_6-8_Transitional_Area',...
'Area_43',...
'Area_OP4-PV',...
'Area_OP1-SII',...
'Area_OP2-3-VS',...
'Area_52',...
'RetroInsular_Cortex',...
'Area_PFcm',...
'Posterior_Insular_Area_2',...
'Area_TA2',...
'Frontal_Opercular_Area_4',...
'Middle_Insular_Area',...
'Pirform_Cortex',...
'Anterior_Ventral_Insular_Area',...
'Anterior_Agranular_Insula_Complex',...
'Frontal_Opercular_Area_1',...
'Frontal_Opercular_Area_3',...
'Frontal_Opercular_Area_2',...
'Area_PFt',...
'Anterior_IntraParietal_Area',...
'Entorhinal_Cortex',...
'PreSubiculum',...
'Hippocampus',...
'ProStriate_Area',...
'Perirhinal_Ectorhinal_Cortex',...
'Area_STGa',...
'ParaBelt_Complex',...
'Auditory_5_Complex',...
'ParaHippocampal_Area_1',...
'ParaHippocampal_Area_3',...
'Area_STSd_anterior',...
'Area_STSd_posterior',...
'Area_STSv_posterior',...
'Area_TG_dorsal',...
'Area_TE1_anterior',...
'Area_TE1_posterior',...
'Area_TE2_anterior',...
'Area_TF',...
'Area_TE2_posterior',...
'Area_PHT',...
'Area_PH',...
'Area_TemporoParietoOccipital_Junction_1',...
'Area_TemporoParietoOccipital_Junction_2',...
'Area_TemporoParietoOccipital_Junction_3',...
'Dorsal_Transitional_Visual_Area',...
'Area_PGp',...
'Area_IntraParietal_2',...
'Area_IntraParietal_1',...
'Area_IntraParietal_0',...
'Area_PF_Opercular',...
'Area_PF_Complex',...
'Area_PFm_Complex',...
'Area_PGi',...
'Area_PGs',...
'Area_V6A',...
'VentroMedial_Visual_Area_1',...
'VentroMedial_Visual_Area_3',...
'ParaHippocampal_Area_2',...
'Area_V4t',...
'Area_FST',...
'Area_V3CD',...
'Area_Lateral_Occipital_3',...
'VentroMedial_Visual_Area_2',...
'Area_31pd',...
'Area_31a',...
'Ventral_Visual_Complex',...
'Area_25',...
'Area_s32',...
'Posterior_OFC_Complex',...
'Area_Posterior_Insular_1',...
'Insular_Granular_Complex',...
'Area_Frontal_Opercular_5',...
'Area_posterior_10p',...
'Area_posterior_47r',...
'Area_TG_Ventral',...
'Medial_Belt_Complex',...
'Lateral_Belt_Complex',...
'Auditory_4_Complex',...
'Area_STSv_anterior',...
'Area_TE1_Middle',...
'Para-Insular_Area',...
'Area_anterior_32_prime',...
'Area_posterior_24'});

HorizontalCompactNudge = 0.07;

if options.UseShortLabels
	APARCShortLabels = {'BSTS', 'CAC', 'CMF', 'CUN', 'ENT', 'FUS', ...
				'INFP', 'IT', 'ISTC', 'LOCC', 'LORB', 'LIN', 'MORB', 'MT', ...
				'PARH', 'PARC', 'POPE', 'PORB', 'PTRI', 'PCAL', 'PSTS', 'PC', ...
				'PREC', 'PCUN', 'RAC', 'RMF', 'SF', 'SP', 'ST', 'SMAR', 'FP', 'TP', 'TT', 'INS'};
	DKTShortLabels = {'CAC', 'CMF', 'CUN', 'ENT', 'FUS', ...
				'INFP', 'IT', 'ISTC', 'LOCC', 'LORB', 'LIN', 'MORB', 'MT', ...
				'PARH', 'PARC', 'POPE', 'PORB', 'PTRI', 'PCAL', 'PSTS', 'PC', ...
				'PREC', 'PCUN', 'RAC', 'RMF', 'SF', 'SP', 'ST', 'SMAR', 'TT', 'INS'};
    HCPMMP1ShortLabels = {'V1_ROI','MST_ROI','V6_ROI','V2_ROI','V3_ROI','V4_ROI','V8_ROI','4_ROI','3b_ROI','FEF_ROI','PEF_ROI','55b_ROI','V3A_ROI','RSC_ROI','POS2_ROI','V7_ROI','IPS1_ROI','FFC_ROI','V3B_ROI','LO1_ROI','LO2_ROI','PIT_ROI','MT_ROI','A1_ROI','PSROI','SFROI','PCV_ROI','STV_ROI','7Pm_ROI','7m_ROI','POS1_ROI','23d_ROI','v23ab_ROI','d23ab_ROI','31pv_ROI','5m_ROI','5mv_ROI','5ROI','23c_ROI','24dd_ROI','24dv_ROI','7AROI','SCEF_ROI','6ma_ROI','7Am_ROI','7PROI','7PC_ROI','LIPv_ROI','VIP_ROI','MIP_ROI','1_ROI','2_ROI','3a_ROI','6d_ROI','6mp_ROI','6v_ROI','p24pr_ROI','33pr_ROI','a24pr_ROI','p32pr_ROI','a24_ROI','d32_ROI','8BM_ROI','p32_ROI','10r_ROI','47m_ROI','8Av_ROI','8Ad_ROI','9m_ROI','8BROI','9p_ROI','10d_ROI','8C_ROI','44_ROI','45_ROI','47ROI','a47r_ROI','6r_ROI','IFJa_ROI','IFJp_ROI','IFSp_ROI','IFSa_ROI','p9-46v_ROI','46_ROI','a9-46v_ROI','9-46d_ROI','9a_ROI','10v_ROI','a10p_ROI','10pp_ROI','11ROI','13ROI','OFC_ROI','47s_ROI','LIPd_ROI','6a_ROI','i6-8_ROI','s6-8_ROI','43_ROI','OP4_ROI','OP1_ROI','OP2-3_ROI','52_ROI','RI_ROI','PFcm_ROI','PoI2_ROI','TA2_ROI','FOP4_ROI','MI_ROI','Pir_ROI','AVI_ROI','AAIC_ROI','FOP1_ROI','FOP3_ROI','FOP2_ROI','PFt_ROI','AIP_ROI','EC_ROI','PreS_ROI','ProS_ROI','PeEc_ROI','STGa_ROI','PBelt_ROI','A5_ROI','PHA1_ROI','PHA3_ROI','STSda_ROI','STSdp_ROI','STSvp_ROI','TGd_ROI','TE1a_ROI','TE1p_ROI','TE2a_ROI','TF_ROI','TE2p_ROI','PHT_ROI','PH_ROI','TPOJ1_ROI','TPOJ2_ROI','TPOJ3_ROI','DVT_ROI','PGp_ROI','IP2_ROI','IP1_ROI','IP0_ROI','PFop_ROI','PF_ROI','PFm_ROI','PGi_ROI','PGs_ROI','V6A_ROI','VMV1_ROI','VMV3_ROI','PHA2_ROI','V4t_ROI','FST_ROI','V3CD_ROI','LO3_ROI','VMV2_ROI','31pd_ROI','31a_ROI','VVC_ROI','25_ROI','s32_ROI','pOFC_ROI','PoI1_ROI','Ig_ROI','FOP5_ROI','p10p_ROI','p47r_ROI','TGv_ROI','MBelt_ROI','LBelt_ROI','A4_ROI','STSva_ROI','TE1m_ROI','PI_ROI','a32pr_ROI','p24_ROI'}
else
	APARCShortLabels = [];
	DKTShortLabels = [];
    HCPMMP1ShortLabels = [];
end

switch(FreesurferSeedType)
	case 'aparc'
		RegionLabels = APARCLabels;
		ShortRegionLabels = APARCShortLabels;
	case 'dkt'
		RegionLabels = DKTLabels;
		ShortRegionLabels = DKTShortLabels;
    case 'HCP-MMP1'
		RegionLabels = HCPMMP1Labels;
		ShortRegionLabels = HCPMMP1ShortLabels;
end

if isempty(ValuesMask) && ismember(FreesurferSeedType, {'aparc', 'dkt','hcpmmp1'})
	ValuesMask = cellfun(@(x) (true(size(x))), RegionLabels, 'UniformOutput', false);
end

if options.LargeFonts
    FontMult = 1.5;
else
    FontMult = 1;
end

Hemis = {'lh', 'rh'};

clf;
FigPos = [1 1 640 480];
%FigPos = [1702 100 1048 850]; % just for multiple monitors
set(gcf, 'Color', 'k', 'Position', FigPos, 'PaperPosition', FigPos, 'PaperUnits', 'points', 'InvertHardCopy', 'off');

switch(options.SurfType)
	case {'pial', 'white'}
		if strcmp(options.SurfaceSource, 'fs6')
			ZoomFactor = 2;
		else
			ZoomFactor = 1;
		end
	case 'inflated'
		if strcmp(options.SurfaceSource, 'fs6')
			ZoomFactor = 2;
		else
			ZoomFactor = 1.25;
		end
end
%#$ZoomFactor = 2; % for inflated
%ZoomFactor = 1; % for pial
clf;
AX = zeros(2, 2);
Patches = zeros(2, 2);

PatchProps = {'EdgeColor', 'none', 'AmbientStrength', 0.8, 'SpecularStrength', 0.1, 'FaceColor', 'interp'};

if(~isempty(options.PatchProps))
	PatchProps = [PatchProps, options.PatchProps];
end

for HemiIDX = 1:length(Hemis)
	AX(HemiIDX, 1) = subplot(2, 2, 1 + (HemiIDX - 1) * 2);
	Patches(HemiIDX, 1) = patch('Vertices', FSAverageV{HemiIDX}, 'Faces', FSAverageF{HemiIDX}, 'FaceVertexCData', FaceVertexCData{HemiIDX}, PatchProps{:});
	axis equal off;
	lighting gouraud;
	view(90 + 180 * (HemiIDX - 1), 0);
	camlight;
	zoom(ZoomFactor);
	%title([Hemis{z} ' ' NeuropsychFieldsOfInterest{NSFieldIDX} ' ' APARCFieldsOfInterest{APARCFieldIDX}], 'Interpreter', 'none');
	AX(HemiIDX, 2) = subplot(2, 2, 2 + (HemiIDX - 1) * 2);
	Patches(HemiIDX, 2) = patch('Vertices', FSAverageV{HemiIDX}, 'Faces', FSAverageF{HemiIDX}, 'FaceVertexCData', FaceVertexCData{HemiIDX}, PatchProps{:});
	axis equal off;
	lighting gouraud;
	view(270 + 180 * (HemiIDX - 1), 0);
	camlight;
	zoom(ZoomFactor);
end
if ~verLessThan('matlab', 'R2016a')
	set(AX, 'Clipping', 'off');
end
%keyboard;
UpNudge = 0.2;
% disp('At start');
% for z = 1:numel(AX)
%     get(AX(z), 'Position')
% end
for z = 1:2
	AXPos = get(AX(2, z), 'Position');
	AXPos(2) = AXPos(2) + UpNudge;
	set(AX(2, z), 'Position', AXPos);
end
%keyboard;
if options.HorizontalCompact
    for z = 1:2
        AXPos = get(AX(z, 1), 'Position');
        AXPos(1) = AXPos(1) + HorizontalCompactNudge;
        set(AX(z, 1), 'Position', AXPos);

        AXPos = get(AX(z, 2), 'Position');
        AXPos(1) = AXPos(1) - HorizontalCompactNudge;
        set(AX(z, 2), 'Position', AXPos);
    end
end
%keyboard;
% disp('At start');
% for z = 1:numel(AX)
%     get(AX(z), 'Position')
% end
%keyboard;
% if ~verLessThan('matlab', 'R2016a')
% 	set(AX, 'Clipping', 'off');
% end
%keyboard;
DoPositionRectangles = false;

if DoPositionRectangles
	Colors = 'rgbm';
	for z = 1:numel(AX)
		AXPos = get(AX(z), 'Position');
		annotation('rectangle', AXPos, 'Color', Colors(z));
	end
end

TopLeftAXPos = get(AX(1, 1), 'Position');
TopRightAXPos = get(AX(1, 2), 'Position');
BottomLeftAXPos = get(AX(2, 1), 'Position');
BottomRightAXPos = get(AX(2, 2), 'Position');

if ~isempty(CMAPX) && ~options.NoLegend
	%keyboard;
	LegAXHeight = 0.05;
	LegAXWidth = 0.2;
	LegAX = axes('Position', [(TopLeftAXPos(1) + TopRightAXPos(1) + TopRightAXPos(3)) / 2 - LegAXWidth / 2, ...
		BottomLeftAXPos(2) - LegAXHeight * 1.5, ...
		LegAXWidth, ...
		LegAXHeight]);
	imshow(CMAPIMG, [], 'YData', (1:size(CMAPIMG, 2)) / 10, 'XData', 1:size(CMAPIMG, 2));
	axis xy on;

	set(gca, 'YTick', [], 'Color', options.BackgroundTextColour, 'XColor', options.BackgroundTextColour, 'XTick', []);

	LegendXTickIDX = interp1(CMAPX, 1:length(CMAPX), LegendXTick);

	%LegendXTickLabels = {'0', ['>= ' num2str(LargestEffectSize, '%.3f')]};
	for z = 1:length(LegendXTickIDX)
		text(LegendXTickIDX(z), -1, LegendXTickLabels{z}, 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top', ...
			'Color', options.BackgroundTextColour, 'FontSize', 18);
	end
	if(~isempty(options.LegendLabel))
		text(0.5, -1.0, options.LegendLabel, 'Color', options.BackgroundTextColour, 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top', 'FontSize', 24 * FontMult, 'FontName', 'Times', 'Units', 'normalized');
	end
end


if options.MedialLateralLabels && ~options.HorizontalCompact
% 	if ~verLessThan('matlab', 'R2017b')
% 		%disp('here');
%
% 	elseif ~verLessThan('matlab', 'R2016a')
% 		if ~options.UseShortLabels
% 			switch(computer)
% 				case 'GLNXA64'
% 					LeftX = -1.2;
% 					RightX = 2.21;
% 				otherwise
% 					LeftX = -1.75;
% 					RightX = 2.5;
% 			end
% 		else
% 			LeftX = -1;
% 			RightX = 2;
% 		end
%
% 	else
% 		LeftX = -0.2;
% 		RightX = 1.21;
% 	end

	%if ~options.UseShortLabels
	%	LeftX = -0.12;
	%	RightX = 0.02;
	if ~verLessThan('matlab', 'R2017b')
		%disp('here');
		LeftX = -0.0;
		RightX = 0.02;
	elseif ~verLessThan('matlab', 'R2016a')
		if ~options.UseShortLabels
			switch(computer)
				case 'GLNXA64'
					LeftX = -1.2;
					RightX = 2.21;
				otherwise
					LeftX = -1.75;
					RightX = 2.5;
			end
		else
			LeftX = -1;
			RightX = 2;
		end

	else
		LeftX = 0.01;
		RightX = -0.04;
	end

	T = {'EdgeColor', 'none', 'FontSize', 20 * FontMult, 'Color', options.BackgroundTextColour, 'Units', 'normalized', 'HorizontalAlignment', 'center'};
	%text( LeftX, 0.275,  'Medial', 'Parent', AX(1, 1), 'Rotation',  90, T{:});
	%text(RightX, 0.275, 'Lateral', 'Parent', AX(1, 2), 'Rotation', 270, T{:});

	TopLAXPos = get(AX(1, 1), 'Position');
	TopRAXPos = get(AX(1, 2), 'Position');
	BotLAXPos = get(AX(2, 1), 'Position');
	BotRAXPos = get(AX(2, 2), 'Position');

	%annotation('textbox', [0, BotLAXPos(2), TopLAXPos(1), TopLAXPos(2) + TopLAXPos(4) - BotLAXPos(2)], ...
	%	'String', 'Medial', T{:});
	T = {'HeadStyle','none','LineStyle', 'none', 'FontSize', 20 * FontMult, 'TextColor', options.BackgroundTextColour, 'HorizontalAlignment', 'center'};
	T = {'FontSize', 20 * FontMult, 'TextColor', options.BackgroundTextColour, 'HorizontalAlignment', 'center'};
    
    XX = [TopLAXPos(1) + LeftX / 2, TopLAXPos(1) + LeftX];
	YY = repmat((TopLAXPos(2) + TopLAXPos(4) + BotLAXPos(2)) / 2, 1, 2);
	annotation('textarrow', XX, YY, 'String', 'Medial', T{:}, 'TextRotation', 90);
	XX = [TopRAXPos(1) + TopRAXPos(3) + RightX, TopRAXPos(1)];
    YY = repmat((TopRAXPos(2) + TopRAXPos(4) + BotRAXPos(2)) / 2, 1, 2);
	annotation('textarrow', XX, YY, 'String', 'Lateral', T{:}, 'TextRotation', 270);

end

% now put the PA arrows and LH and RH labels

TopLeftAXPos = get(AX(1, 1), 'Position');
TopRightAXPos = get(AX(1, 2), 'Position');
BottomLeftAXPos = get(AX(2, 1), 'Position');
BottomRightAXPos = get(AX(2, 2), 'Position');

ArrowProps = {'Color', options.BackgroundTextColour, 'LineWidth', 2};
if options.HorizontalCompact
    TextFontSize = 28;
else
    TextFontSize = 20;
end
TextProps = {'Color', options.BackgroundTextColour, 'LineStyle', 'none', 'EdgeColor', options.LabelColour, 'VerticalAlignment', 'middle', 'FontSize', 28};

ArrowFigWidthProp = 0.35;
if(options.UseShortLabels)
	ArrowFigBotNudge = 0.075;
	ArrowFigTopNudge = 0.135;
else
	ArrowFigBotNudge = 0.1;
	ArrowFigTopNudge = 0.095;
end
AnnotHeight = 0.2;


annotation('textbox', 'Position', [(TopLeftAXPos(1) + TopRightAXPos(1) + TopRightAXPos(3)) / 2 - 0.01, ...
	TopLeftAXPos(2) + TopLeftAXPos(4) - ArrowFigTopNudge, ...
	0.02, ...
	AnnotHeight], 'String', 'LH', 'Color', options.LabelColour, TextProps{:}, 'HorizontalAlignment', 'center');
annotation('textbox', 'Position', [(BottomLeftAXPos(1) + BottomRightAXPos(1) + BottomRightAXPos(3)) / 2 - 0.01, ...
	BottomLeftAXPos(2) - ArrowFigBotNudge, ...
	0.02, ...
	AnnotHeight], 'String', 'RH', 'Color', options.LabelColour, TextProps{:}, 'HorizontalAlignment', 'center');

% top left
annotation('doublearrow', [TopLeftAXPos(1) + TopLeftAXPos(3) * ArrowFigWidthProp, TopLeftAXPos(1) + TopLeftAXPos(3) * (1 - ArrowFigWidthProp)], ...
	repmat(TopLeftAXPos(2) + TopLeftAXPos(4) - ArrowFigTopNudge + 0.1, 1, 2), ArrowProps{:});
annotation('textbox', [TopLeftAXPos(1), TopLeftAXPos(2) + TopLeftAXPos(4) - ArrowFigTopNudge, TopLeftAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'P', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'right');
annotation('textbox', [TopLeftAXPos(1) + TopLeftAXPos(3) * (1 - ArrowFigWidthProp), TopLeftAXPos(2) + TopLeftAXPos(4) - ArrowFigTopNudge, TopLeftAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'A', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'left');

% bottom left
annotation('doublearrow', [BottomLeftAXPos(1) + BottomLeftAXPos(3) * ArrowFigWidthProp, BottomLeftAXPos(1) + BottomLeftAXPos(3) * (1 - ArrowFigWidthProp)], ...
	repmat(BottomLeftAXPos(2), 1, 2) + 0.1 - ArrowFigBotNudge, ArrowProps{:});
annotation('textbox', [BottomLeftAXPos(1), BottomLeftAXPos(2) - ArrowFigBotNudge, BottomLeftAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'A', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'right', ...
    'FontSize', 28);
annotation('textbox', [BottomLeftAXPos(1) + BottomLeftAXPos(3) * (1 - ArrowFigWidthProp), BottomLeftAXPos(2) - ArrowFigBotNudge, BottomLeftAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'P', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'left');

% top right
annotation('doublearrow', [TopRightAXPos(1) + TopRightAXPos(3) * ArrowFigWidthProp, TopRightAXPos(1) + TopRightAXPos(3) * (1 - ArrowFigWidthProp)], ...
	repmat(TopRightAXPos(2) + TopRightAXPos(4) - ArrowFigTopNudge + 0.1, 1, 2), ArrowProps{:});
annotation('textbox', [TopRightAXPos(1), TopRightAXPos(2) + TopRightAXPos(4) - ArrowFigTopNudge, TopRightAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'A', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'right');
annotation('textbox', [TopRightAXPos(1) + TopRightAXPos(3) * (1 - ArrowFigWidthProp), TopRightAXPos(2) + TopRightAXPos(4) - ArrowFigTopNudge, TopRightAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'P', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'left');

% bottom right
annotation('doublearrow', [BottomRightAXPos(1) + BottomRightAXPos(3) * ArrowFigWidthProp, BottomRightAXPos(1) + BottomRightAXPos(3) * (1 - ArrowFigWidthProp)], ...
	repmat(BottomRightAXPos(2) + 0.1 - ArrowFigBotNudge, 1, 2), ArrowProps{:});
annotation('textbox', [BottomRightAXPos(1), BottomRightAXPos(2) - ArrowFigBotNudge, BottomRightAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'P', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'right');
annotation('textbox', [BottomRightAXPos(1) + BottomRightAXPos(3) * (1 - ArrowFigWidthProp), BottomRightAXPos(2) - ArrowFigBotNudge, BottomRightAXPos(3) * ArrowFigWidthProp, AnnotHeight], ...
	'String', 'A', ...
	TextProps{:}, ...
	'HorizontalAlignment', 'left');
%NoLabels = false;

% title
if(~isempty(options.MainTitle))
	T = 0.45;
	annotation('textbox', 'Position', [(TopLeftAXPos(1) + TopRightAXPos(1) + TopRightAXPos(3)) / 2 - T / 2, ...
		TopLeftAXPos(2) + TopLeftAXPos(4), ...
		T, ...
		1 - (TopLeftAXPos(2) + TopLeftAXPos(4))], ...
		'String', options.MainTitle, ...
		'Color', options.BackgroundTextColour, 'HorizontalAlignment', 'center', 'FontSize', 18 * FontMult, 'VerticalAlignment', 'middle', 'EdgeColor', 'none');
end

if(~options.NoLabels)
	if(ismember(lower(FreesurferSeedType), {'aparc', 'dkt'}))
		if(iscell(ShortRegionLabels))
			FontWeight = 'bold';
			FontSize = 10 * FontMult;
		else
			switch(computer)
					case {'PCWIN64', 'GLNXA64'}
						FontWeight = 'normal';
						FontSize = 8 * FontMult;
					otherwise
						FontWeight = 'bold';
						FontSize = 10 * FontMult;
			end
		end

		LabelTextBoxPropsDone = {'FitBoxToText', 'off', ...
			'Margin', 2, ...
			'Color', options.LabelColour, 'EdgeColor', 'none', 'LineStyle', 'none', ...
			'VerticalAlignment', 'middle', ...
			'HorizontalAlignment', 'center', ...
			'FontWeight', FontWeight, ...
			'FontSize', FontSize};

		ArrowProps = {'LineWidth', 2, 'Color', 'w'};

		if (verLessThan('matlab', 'r2017a'))
			RectProps = {'FaceColor', 'flat', 'EdgeColor', options.LabelColour, 'LineWidth', 2};
		else
			RectProps = {'FaceColor', 'none', 'EdgeColor', options.LabelColour, 'LineWidth', 2};
		end
		% Create textbox
		%LabelTextBoxPropsDone = [LabelTextBoxProps {'Color', options.LabelColour}];
		%RectProps
		switch(options.SurfaceSource)
			case 'fs6'
				freesurfer_statsurf_textboxes_func = @freesurfer_statsurf_textboxes_fs6;
			case 'mcribs'
				freesurfer_statsurf_textboxes_func = @freesurfer_statsurf_textboxes_mcribs;
		end
		[TextBoxes, Arrows, Rectangles] = freesurfer_statsurf_textboxes_func(FreesurferSeedType);
		if(iscell(ShortRegionLabels))
			ShortRegionLabelsLegendStrings = cell(1000, 1);
			ShortRegionLabelsLegendStringsIDX = 1;
		end
		for HemiIDX = 1:length(Hemis)
			Hemi = upper(Hemis{HemiIDX});
			F = RegionLabels{HemiIDX};

			for CurField = 1:length(F)
				if(ValuesMask{HemiIDX}(CurField))
					if(iscell(ShortRegionLabels))
						% put the abbreviations in instead of the main boxes
						HasArrow = isfield(Arrows.(Hemi), F{CurField});
						HasTextBox = isfield(TextBoxes.(Hemi), F{CurField});
						%HasRectangle = isfield(Rectangles.(Hemi), F{CurField});


						if(HasArrow || HasTextBox)
							% if there is an arrow then put it at the center of the
							% arrow endpoint
							NumTextBoxes = length(TextBoxes.(Hemi).(F{CurField}));
							if(HasArrow)
								XIDX = find(strcmp('X', Arrows.(Hemi).(F{CurField})(1:2:end))); % find 'X' in the parameters, which are in the odd indices
								XIDX = (XIDX - 1) * 2 + 1; % so find the original index that it is in
								CurX = Arrows.(Hemi).(F{CurField}){XIDX + 1};
								YIDX = find(strcmp('Y', Arrows.(Hemi).(F{CurField})(1:2:end))); % find 'X' in the parameters, which are in the odd indices
								YIDX = (YIDX - 1) * 2 + 1; % so find the original index that it is in
								CurY = Arrows.(Hemi).(F{CurField}){YIDX + 1};

								TextBoxesCentroid = [CurX(2), CurY(2)];
							elseif(HasTextBox)
								% if there are textboxes but no arrows, then find
								% the centroid of the textboxes

								TextBoxesCentroid = zeros(NumTextBoxes, 2);
								for CurTextBox = 1:NumTextBoxes
									PositionIDX = find(strcmp('Position', TextBoxes.(Hemi).(F{CurField}){CurTextBox}(1:2:end))); % find 'Position' in the parameters, which are in the odd indices
									PositionIDX = (PositionIDX - 1) * 2 + 1; % so find the original index that it is in
									TextBoxPosition = TextBoxes.(Hemi).(F{CurField}){CurTextBox}{PositionIDX + 1};
									TextBoxesCentroid(CurTextBox, :) = [TextBoxPosition(1) + TextBoxPosition(3) / 2, TextBoxPosition(2) + TextBoxPosition(4) / 2];
								end
								TextBoxesCentroid = mean(TextBoxesCentroid, 1);
                            end
                            if options.HorizontalCompact
                                if TextBoxesCentroid(1) < 0.5
                                    TextBoxesCentroid(1) = TextBoxesCentroid(1) + HorizontalCompactNudge;
                                else
                                    TextBoxesCentroid(1) = TextBoxesCentroid(1) - HorizontalCompactNudge;
                                end
                            end
							TextBoxWidthHeight = [0.2, 0.1];
							annotation('textbox', 'Position', [TextBoxesCentroid(1) - TextBoxWidthHeight(1) / 2, TextBoxesCentroid(2) - TextBoxWidthHeight(2) / 2, TextBoxWidthHeight], ...
								'String', ShortRegionLabels{CurField}, LabelTextBoxPropsDone{:});
							CurString = cell(1, NumTextBoxes);

							for CurTextBox = 1:NumTextBoxes
								StringIDX = find(strcmp('String', TextBoxes.(Hemi).(F{CurField}){CurTextBox}(1:2:end)));
								StringIDX = (StringIDX - 1) * 2 + 1;
								CurString{CurTextBox} = TextBoxes.(Hemi).(F{CurField}){CurTextBox}{StringIDX + 1};
							end
							% now CurString will be a cell array, so we
							% need to join it with spaces
							CurString = cat(1, CurString{:});
							CurString = deblank(sprintf('%s ', CurString{:}));
							CurString = strrep(CurString, '- ', '');
							ShortRegionLabelsLegendStrings{ShortRegionLabelsLegendStringsIDX} = [ShortRegionLabels{CurField} ': ' CurString ', '];
							ShortRegionLabelsLegendStringsIDX = ShortRegionLabelsLegendStringsIDX + 1;
						end
					else
						if(isfield(TextBoxes.(Hemi), F{CurField}))
							for CurBox = 1:length(TextBoxes.(Hemi).(F{CurField}))
								annotation('textbox', LabelTextBoxPropsDone{:}, TextBoxes.(Hemi).(F{CurField}){CurBox}{:});
							end
						end
						if(isfield(Arrows.(Hemi), F{CurField}))
							annotation('arrow', Arrows.(Hemi).(F{CurField}){:}, ArrowProps{:});
						end
						if(isfield(Rectangles.(Hemi), F{CurField}))

							annotation('rectangle', Rectangles.(Hemi).(F{CurField}){:}, RectProps{:});
						end
					end
				end
			end
		end
		if(iscell(ShortRegionLabels))
			ShortRegionLabelsLegendStrings = ShortRegionLabelsLegendStrings(1:ShortRegionLabelsLegendStringsIDX - 1);
			%keyboard;
			ShortRegionLabelsLegendStrings = unique(ShortRegionLabelsLegendStrings);
			ShortRegionLabelsLegendStrings = cat(2, ShortRegionLabelsLegendStrings{:});
			disp(ShortRegionLabelsLegendStrings(1:end - 2));
		end
	end
end

% disp('At end');
% for z = 1:numel(AX)
%     get(AX(z), 'Position')
% end

%keyboard;
